imports:
  - { resource: services/assets.yml }
  - { resource: services/authentication.yml }
  - { resource: services/cases.yml }
  - { resource: services/camunda.yml }
  - { resource: services/cms.yml }
  - { resource: services/formio.yml }
  - { resource: services/identities.yml }
  - { resource: services/records.yml }
  - { resource: services/services.yml }
  - { resource: services/tasks.yml }

services:
  ds_api.api:
    class: '%ds_api.api.class%'
    arguments:
      - '@ds_api.collection.service'
      - '@ds_discovery.service.discovery'
      - '@ds_config.service.config'
      - '@lexik_jwt_authentication.jwt_manager'

  ds_api.client:
    class: '%ds_api.client.class%'

  ds_api.service:
    abstract: true
    arguments:
      - '@ds_api.client'
    public: false
