services:
  ds_tenant.service.tenant:
    class: '%ds_tenant.service.tenant.class%'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ds_config.service.parameter'
      - '@request_stack'
      - '@security.token_storage'
      - '@ds_tenant.collection.loader'
      - '@ds_tenant.collection.unloader'
      - '%ds_tenant.entity.tenant.class%'
