services:
  ds_security.serializer.normalizer.acl.property:
    decorates: api_platform.serializer.normalizer.item
    class: '%ds_security.serializer.normalizer.acl.property.class%'
    arguments:
      - '@ds_security.serializer.normalizer.acl.property.inner'
      - '@security.token_storage'
      - '@ds_security.voter.permission.property'

  ds_security.serializer.jsonld.normalizer.acl.property:
    decorates: api_platform.jsonld.normalizer.item
    class: '%ds_security.serializer.normalizer.acl.property.class%'
    arguments:
      - '@ds_security.serializer.jsonld.normalizer.acl.property.inner'
      - '@security.token_storage'
      - '@ds_security.voter.permission.property'
