services:
  ds_security.voter.permission.generic:
    class: '%ds_security.voter.permission.generic.class%'
    arguments:
      - '@ds_security.service.access'
      - '@ds_security.collection.permission'
    tags:
      - { name: security.voter }

  ds_security.voter.permission.entity:
    class: '%ds_security.voter.permission.entity.class%'
    arguments:
      - '@ds_security.service.access'
    tags:
      - { name: security.voter }

  ds_security.voter.permission.property:
    class: '%ds_security.voter.permission.property.class%'
    arguments:
      - '@ds_security.service.access'
    tags:
      - { name: security.voter }

  ds_security.voter.deleted:
    class: '%ds_security.voter.deleted.class%'
    tags:
      - { name: security.voter }

  ds_security.voter.enabled:
    class: '%ds_security.voter.enabled.class%'
    tags:
      - { name: security.voter }
