services:
    ds_security.event_listener.token.uuid:
        class: Ds\Component\Security\EventListener\Token\UuidListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }
