services:
  ds_discovery.client:
    class: '%ds_discovery.client.class%'

  ds_discovery.repository.config:
    class: '%ds_discovery.repository.config.class%'
    arguments:
      - '@ds_discovery.client'
      - '%discovery_host%'
      - '%discovery_credential%'
      - '%namespace%'
