services:
    ds_api.service.camunda.process_definition:
        parent: ds_api.service
        class: '%ds_api.service.camunda.process_definition.class%'
        tags:
            - { name: ds_api.service, alias: camunda.process_definition }

    ds_api.service.camunda.process_instance:
        parent: ds_api.service
        class: '%ds_api.service.camunda.process_instance.class%'
        tags:
            - { name: ds_api.service, alias: camunda.process_instance }

    ds_api.service.camunda.task:
        parent: ds_api.service
        class: '%ds_api.service.camunda.task.class%'
        tags:
            - { name: ds_api.service, alias: camunda.task }

    ds_api.service.camunda.task.variable:
        parent: ds_api.service
        class: '%ds_api.service.camunda.task.variable.class%'
        tags:
            - { name: ds_api.service, alias: camunda.task.variable }
