services:
    ds_api.service.formio.authentication:
        parent: ds_api.service
        class: '%ds_api.service.formio.authentication.class%'
        tags:
            - { name: ds_api.service, alias: formio.authentication }

    ds_api.service.formio.project:
        parent: ds_api.service
        class: '%ds_api.service.formio.project.class%'
        tags:
            - { name: ds_api.service, alias: formio.project }

    ds_api.service.formio.form:
        parent: ds_api.service
        class: '%ds_api.service.formio.form.class%'
        tags:
            - { name: ds_api.service, alias: formio.form }

    ds_api.service.formio.submission:
        parent: ds_api.service
        class: '%ds_api.service.formio.submission.class%'
        tags:
            - { name: ds_api.service, alias: formio.submission }

    ds_api.service.formio.user:
        parent: ds_api.service
        class: '%ds_api.service.formio.user.class%'
        tags:
            - { name: ds_api.service, alias: formio.user }

    ds_api.service.formio.role:
        parent: ds_api.service
        class: '%ds_api.service.formio.role.class%'
        tags:
            - { name: ds_api.service, alias: formio.role }
