services:
  ds_tenant.service.tenant:
    class: '%ds_tenant.service.tenant.class%'
    arguments:
      - '@ds_config.service.parameter'
      - '@request_stack'
      - '@security.token_storage'
      - '@ds_tenant.collection.loader'
