doctrine:
    orm:
        mappings:
            DsSecurity:
                type: annotation
                is_bundle: false
                dir: %kernel.root_dir%/../vendor/digitalstate/core/src/Ds/Component/Security/Entity
                prefix: Ds\Component\Security\Entity
                alias: DsSecurity

doctrine_cache:
    providers:
        ds_security_query:
            apc: ~
            namespace: ds_security_query
            aliases:
                - ds_security.doctrine.cache.query

ds_security:
    token:
        uuid: true
        identity: true
        identity_uuid: true
        ip: false
        client: false
        modifier: false

    filter:
        identity: false
        anonymous: false
        individual: false
        owner: false
        enabled: false
