doctrine:
    orm:
        mappings:
            DsSecurity:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../vendor/digitalstate/core/src/Ds/Component/Security/Entity'
                prefix: Ds\Component\Security\Entity
                alias: DsSecurity

ds_security:
    permissions:
        custom:                { title: ds.security.permissions.custom,                  custom:   '*',                                                attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE] }
        entity:                { title: ds.security.permissions.entity,                  entity:   '*',                                                attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        property:              { title: ds.security.permissions.property,                property: '*.*',                                              attributes: [BROWSE, READ, EDIT] }
        access:                { title: ds.security.permissions.access,                  entity:   Ds\Component\Security\Entity\Access,                attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        access_property:       { title: ds.security.permissions.access.property,         property: Ds\Component\Security\Entity\Access.*,              attributes: [BROWSE, READ, EDIT] }
        access_id:             { title: ds.security.permissions.access.id,               property: Ds\Component\Security\Entity\Access.id,             attributes: [BROWSE, READ, EDIT] }
        access_uuid:           { title: ds.security.permissions.access.uiid,             property: Ds\Component\Security\Entity\Access.uuid,           attributes: [BROWSE, READ, EDIT] }
        access_created_at:     { title: ds.security.permissions.access.created_at,       property: Ds\Component\Security\Entity\Access.createdAt,      attributes: [BROWSE, READ, EDIT] }
        access_updated_at:     { title: ds.security.permissions.access.updated_at,       property: Ds\Component\Security\Entity\Access.updatedAt,      attributes: [BROWSE, READ, EDIT] }
        access_owner:          { title: ds.security.permissions.access.owner,            property: Ds\Component\Security\Entity\Access.owner,          attributes: [BROWSE, READ, EDIT] }
        access_owner_uuid:     { title: ds.security.permissions.access.owner_uuid,       property: Ds\Component\Security\Entity\Access.ownerUuid,      attributes: [BROWSE, READ, EDIT] }
        access_identity:       { title: ds.security.permissions.access.identity,         property: Ds\Component\Security\Entity\Access.identity,       attributes: [BROWSE, READ, EDIT] }
        access_identity_uuid:  { title: ds.security.permissions.access.identity_uuid,    property: Ds\Component\Security\Entity\Access.identityUuid,   attributes: [BROWSE, READ, EDIT] }
        access_permissions:    { title: ds.security.permissions.access.permissions,      property: Ds\Component\Security\Entity\Access.permissions,    attributes: [BROWSE, READ, EDIT] }
        permissions:           { title: ds.security.permissions.permissions,             custom:   permissions,                                        attributes: [BROWSE, READ] }
