services:
    ds_security.event_listener.acl.entity:
        class: '%ds_security.event_listener.acl.entity.class%'
        arguments:
            - '@security.token_storage'
            - '@ds_security.voter.permission.entity'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 1 }

    ds_security.event_listener.access.permissions:
        class: '%ds_security.event_listener.access.permissions.class%'
        arguments:
            - '@ds_security.service.access'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 4 }

    ds_security.event_listener.permission.subject:
        class: '%ds_security.event_listener.permission.subject.class%'
        arguments:
            - '@ds_security.collection.permission'
        tags:
            - { name: doctrine.orm.entity_listener, entity: '%ds_security.entity.permission.class%', event: postLoad }

    ds_security.event_listener.token.uuid:
        class: '%ds_security.event_listener.token.uuid.class%'
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: created }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: decoded }

    ds_security.event_listener.token.identity:
        class: '%ds_security.event_listener.token.identity.class%'
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: created }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: decoded }

    ds_security.event_listener.token.identity_uuid:
        class: '%ds_security.event_listener.token.identity_uuid.class%'
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: created }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: decoded }

    ds_security.event_listener.token.ip:
        class: '%ds_security.event_listener.token.ip.class%'
        arguments:
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: created }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: decoded }

    ds_security.event_listener.token.client:
        class: '%ds_security.event_listener.token.client.class%'
        arguments:
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: created }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: decoded }

    ds_security.event_listener.token.modifier:
        class: '%ds_security.event_listener.token.modifier.class%'
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: created }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: decoded }
