parameters:
    ds_security.collection.permission.class: Ds\Component\Security\Collection\PermissionCollection
    ds_security.entity.access.class: Ds\Component\Security\Entity\Access
    ds_security.entity.permission.class: Ds\Component\Security\Entity\Permission
    ds_security.doctrine.orm.query_extension.anonymous.class: Ds\Component\Security\Doctrine\ORM\QueryExtension\AnonymousExtension
    ds_security.doctrine.orm.query_extension.individual.class: Ds\Component\Security\Doctrine\ORM\QueryExtension\IndividualExtension
    ds_security.event_listener.access.permissions.class: Ds\Component\Security\EventListener\Access\PermissionsListener
    ds_security.event_listener.permission.subject.class: Ds\Component\Security\EventListener\Permission\SubjectListener
    ds_security.event_listener.token.uuid.class: Ds\Component\Security\EventListener\Token\UuidListener
    ds_security.event_listener.token.identity.class: Ds\Component\Security\EventListener\Token\IdentityListener
    ds_security.event_listener.token.identity_uuid.class: Ds\Component\Security\EventListener\Token\IdentityUuidListener
    ds_security.event_listener.token.ip.class: Ds\Component\Security\EventListener\Token\IpListener
    ds_security.event_listener.token.client.class: Ds\Component\Security\EventListener\Token\ClientListener
    ds_security.event_listener.token.modifier.class: Ds\Component\Security\EventListener\Token\ModifierListener
    ds_security.serializer.normalizer.acl.class: Ds\Component\Security\Serializer\Normalizer\AclNormalizer
    ds_security.repository.access.class: Ds\Component\Security\Repository\AccessRepository
    ds_security.repository.permission.class: Ds\Component\Security\Repository\PermissionRepository
    ds_security.service.access.class: Ds\Component\Security\Service\AccessService
    ds_security.service.permission.class: Ds\Component\Security\Service\PermissionService
    ds_security.voter.permission.entity.class: Ds\Component\Security\Voter\Permission\EntityVoter
    ds_security.voter.permission.property.class: Ds\Component\Security\Voter\Permission\PropertyVoter
