parameters:
    ds_security.collection.permission.class: Ds\Component\Security\Collection\PermissionCollection
    ds_security.entity.access.class: Ds\Component\Security\Entity\Access
    ds_security.entity.permission.class: Ds\Component\Security\Entity\Permission
    ds_security.doctrine.orm.query_extension.enabled.class: Ds\Component\Security\Doctrine\ORM\QueryExtension\EnabledExtension
    ds_security.doctrine.orm.query_extension.deleted.class: Ds\Component\Security\Doctrine\ORM\QueryExtension\DeletedExtension
    ds_security.doctrine.orm.query_extension.identity.class: Ds\Component\Security\Doctrine\ORM\QueryExtension\IdentityExtension
    ds_security.event_listener.acl.entity.class: Ds\Component\Security\EventListener\Acl\EntityListener
    ds_security.event_listener.access.permissions.class: Ds\Component\Security\EventListener\Access\PermissionsListener
    ds_security.event_listener.permission.value.class: Ds\Component\Security\EventListener\Permission\ValueListener
    ds_security.event_listener.token.uuid.class: Ds\Component\Security\EventListener\Token\UuidListener
    ds_security.event_listener.token.identity.class: Ds\Component\Security\EventListener\Token\IdentityListener
    ds_security.event_listener.token.identity_uuid.class: Ds\Component\Security\EventListener\Token\IdentityUuidListener
    ds_security.event_listener.token.ip.class: Ds\Component\Security\EventListener\Token\IpListener
    ds_security.event_listener.token.client.class: Ds\Component\Security\EventListener\Token\ClientListener
    ds_security.event_listener.token.modifier.class: Ds\Component\Security\EventListener\Token\ModifierListener
    ds_security.serializer.normalizer.acl.property.class: Ds\Component\Security\Serializer\Normalizer\Acl\PropertyNormalizer
    ds_security.repository.access.class: Ds\Component\Security\Repository\AccessRepository
    ds_security.repository.permission.class: Ds\Component\Security\Repository\PermissionRepository
    ds_security.service.access.class: Ds\Component\Security\Service\AccessService
    ds_security.service.permission.class: Ds\Component\Security\Service\PermissionService
    ds_security.voter.custom.class: Ds\Component\Security\Voter\CustomVoter
    ds_security.voter.entity.class: Ds\Component\Security\Voter\EntityVoter
    ds_security.voter.property.class: Ds\Component\Security\Voter\PropertyVoter
