services:
    ds_security.voter.permission.property:
        class: '%ds_security.voter.permission.property.class%'
        arguments:
            - '@ds_security.service.access'
        tags:
           - { name: security.voter }
