services:
  ds_config.filter.config.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        key: partial
    tags:
      - { name: api_platform.filter, id: ds_config.config.search }

  ds_config.filter.config.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
    tags:
      - { name: api_platform.filter, id: ds_config.config.date }

  ds_config.filter.config.boolean:
    parent: api_platform.doctrine.orm.boolean_filter
    arguments: []
    tags:
      - { name: api_platform.filter, id: ds_config.config.boolean }
