services:
    ds_api.http.client:
        class: GuzzleHttp\Client

    ds_api.service:
        abstract: true
        arguments:
            - '@ds_api.http.client'

    ds_api.service.health:
        parent: ds_api.service
        class: '%ds_api.service.health.class%'

    ds_api.service.config:
        parent: ds_api.service
        class: '%ds_api.service.config.class%'

    ds_api.service.access:
        parent: ds_api.service
        class: '%ds_api.service.access.class%'

    ds_api.service.permission:
        parent: ds_api.service
        class: '%ds_api.service.permission.class%'

    ds_api.service.user:
        parent: ds_api.service
        class: '%ds_api.service.user.class%'

    ds_api.service.admin:
        parent: ds_api.service
        class: '%ds_api.service.admin.class%'

    ds_api.service.anonymous:
        parent: ds_api.service
        class: '%ds_api.service.anonymous.class%'

    ds_api.service.individual:
        parent: ds_api.service
        class: '%ds_api.service.individual.class%'

    ds_api.service.staff:
        parent: ds_api.service
        class: '%ds_api.service.staff.class%'

    ds_api.service.system:
        parent: ds_api.service
        class: '%ds_api.service.system.class%'

    ds_api.service.business_unit:
        parent: ds_api.service
        class: '%ds_api.service.business_unit.class%'

    ds_api.service.case:
        parent: ds_api.service
        class: '%ds_api.service.case.class%'

    ds_api.service.case_status:
        parent: ds_api.service
        class: '%ds_api.service.case_status.class%'

    ds_api.service.record:
        parent: ds_api.service
        class: '%ds_api.service.record.class%'

    ds_api.service.asset:
        parent: ds_api.service
        class: '%ds_api.service.asset.class%'

    ds_api.service.category:
        parent: ds_api.service
        class: '%ds_api.service.category.class%'

    ds_api.service.scenario:
        parent: ds_api.service
        class: '%ds_api.service.scenario.class%'

    ds_api.service.service:
        parent: ds_api.service
        class: '%ds_api.service.service.class%'

    ds_api.service.submission:
        parent: ds_api.service
        class: '%ds_api.service.submission.class%'

    ds_api.service.data:
        parent: ds_api.service
        class: '%ds_api.service.data.class%'

    ds_api.service.file:
        parent: ds_api.service
        class: '%ds_api.service.file.class%'

    ds_api.service.text:
        parent: ds_api.service
        class: '%ds_api.service.text.class%'

    ds_api.api:
        class: '%ds_api.api.api.class%'
        arguments:
            - '@ds_api.http.client'
