doctrine:
  orm:
    mappings:
      DsConfig:
        type: annotation
        is_bundle: false
        dir: '%kernel.root_dir%/../vendor/digitalstate/core/src/Ds/Component/Config/Entity'
        prefix: Ds\Component\Config\Entity
        alias: DsConfig

ds_security:
  permissions:
    config:            { attributes: [BROWSE, READ, EDIT, ADD, DELETE], entity:   Ds\Component\Config\Entity\Config,           title: ds.config.permissions.config            }
    config_property:   { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Config\Entity\Config.*,         title: ds.config.permissions.config.property   }
    config_id:         { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Config\Entity\Config.id,        title: ds.config.permissions.config.id         }
    config_uuid:       { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Config\Entity\Config.uuid,      title: ds.config.permissions.config.uuid       }
    config_owner:      { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Config\Entity\Config.owner,     title: ds.config.permissions.config.owner      }
    config_owner_uuid: { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Config\Entity\Config.ownerUuid, title: ds.config.permissions.config.owner_uuid }
    config_key:        { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Config\Entity\Config.key,       title: ds.config.permissions.config.key        }
    config_value:      { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Config\Entity\Config.value,     title: ds.config.permissions.config.value      }
    config_enabled:    { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Config\Entity\Config.enabled,   title: ds.config.permissions.config.enabled    }
    config_version:    { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Config\Entity\Config.version,   title: ds.config.permissions.config.version    }
    config_tenant:     { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Config\Entity\Config.tenant,    title: ds.config.permissions.config.tenant     }
